package com.riverauction.riverauction.api.model;

public enum CErrorCause {
    UNKNOWN,
    NETWORK_ERROR,
    INVALID_ARGUMENT,
    INSUFFICIENT_PERMISSION,
    NO_SUCH_ELEMENT,
    BAD_REQUEST,
    NOT_ALLOWED,
    TEMPORARY_UNAVAILABLE,

    INVALID_EMAIL_FORMAT,
    INVALID_PASSWORD_FORMAT,

    INVALID_TOKEN,
    EXPIRED_TOKEN,
    REVOKED_TOKEN,
    REISSUE_TOKEN,

    ELEMENT_ALREADY_EXISTS,
    REMOVED_USER,
    PASSWORD_NOT_MATCHED,
    TRAVEL_PREFERENCE_LIMIT_EXCESS,
    EXPIRED_LESSON_DEALING,
    EXPIRED_LESSON_BIDDING,
    WRONG_RECEIPT,
    INSUFFICIENT_COINS
}
